# Model
EPISODES = 100
ACTION_STEPS = 3
STATE_SPACE = 9
TRAIN_DQN = True
MAX_STEPS_PER_EPISODE = 1000

# Window
WINDOW_WIDTH = 600
WINDOW_HEIGHT = 600

# Paddle
PADDLE_SHAPE = 'square'
PADDLE_STRETCH_LENGTH = 6
PADDLE_COLOR = 'white'
PADDLE_Y_POS = -280

# Ball
BALL_SHAPE = 'circle'
BALL_COLOR = 'red'
BALL_Y_POS = 100

# Score
SCORE_COLOR = 'white'
SCORE_Y_POS = 280

# Obstacle
OBSTACLE_SHAPE = 'square'
OBSTACLE_COLOR = 'white'
